# Generated by Django 5.0.6 on 2024-07-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'verbose_name': 'Subcategoria', 'verbose_name_plural': 'Subcategorias'},
        ),
        migrations.AlterModelTable(
            name='subcategoria',
            table='subcategorias',
        ),
    ]
