# Generated by Django 5.0.6 on 2024-05-31 18:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('conta', '0002_alter_conta_descricao'),
        ('subcategorias', '0001_initial'),
        ('transacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.conta'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcategorias.subcategoria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('P', 'Pix'), ('C', 'Crédito'), ('D', 'Dinheiro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
