# Generated by Django 5.0.6 on 2024-05-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0002_alter_transacao_categoria_alter_transacao_conta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=1),
        ),
    ]
