# Generated by Django 5.0.6 on 2024-06-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0004_transacaoparcelada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(blank=True, max_length=3)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transacao_parcelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacoes.transacaoparcelada')),
            ],
        ),
    ]
