# Generated by Django 5.0.6 on 2024-06-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0005_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='numero_parcela',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
