# Generated by Django 5.0.6 on 2024-06-04 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0006_alter_parcela_numero_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
