# Generated by Django 5.0.6 on 2024-06-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0008_alter_transacaoparcelada_parcelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacaoparcelada',
            name='tipo',
        ),
    ]
