# Generated by Django 5.0.6 on 2024-06-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0010_parcela_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcela',
            name='usuario',
        ),
    ]
