# Generated by Django 5.0.6 on 2024-07-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0012_parcela_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Paga')], default=1),
        ),
    ]
