# Generated by Django 5.0.6 on 2024-08-02 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoria_options_alter_categoria_table'),
        ('subcategorias', '0002_alter_subcategoria_options_alter_subcategoria_table'),
        ('transacoes', '0014_alter_parcela_options_alter_transacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subcategorias.subcategoria'),
        ),
        migrations.AlterField(
            model_name='transacaoparcelada',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria'),
        ),
        migrations.AlterField(
            model_name='transacaoparcelada',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subcategorias.subcategoria'),
        ),
    ]
