# Generated by Django 5.1 on 2024-08-23 14:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_alter_categoria_tipo'),
        ('conta', '0004_alter_conta_options_alter_conta_table'),
        ('subcategorias', '0002_alter_subcategoria_options_alter_subcategoria_table'),
        ('transacoes', '0016_transacao_conta_destino_alter_transacao_conta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(default='D', max_length=1)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_transacao_modelo', to='conta.conta', verbose_name='conta_transacao_modelo')),
                ('conta_destino', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conta_destino_transacao_modelo', to='conta.conta', verbose_name='conta_destino_transacao_modelo')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subcategorias.subcategoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TransacaoModelo',
                'verbose_name_plural': 'TransacoesModelo',
                'db_table': 'transacao_modelo',
            },
        ),
    ]
