# Generated by Django 5.1 on 2024-08-25 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0017_transacaomodelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacaomodelo',
            name='data',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
