# Generated by Django 5.0.6 on 2024-08-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoria_options_alter_categoria_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(blank=True, choices=[(1, 'Receita'), (2, 'Despesa')], default=None, max_length=255, null=True),
        ),
    ]
