# Generated by Django 5.0.6 on 2024-08-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Receita'), (2, 'Despesa')], default=None, null=True),
        ),
    ]
