# Generated by Django 5.0.6 on 2024-06-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_alter_conta_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='limite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='conta',
            name='limite_atual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
