# Generated by Django 5.0.6 on 2024-07-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_conta_limite_conta_limite_atual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta',
            options={'verbose_name': 'Conta', 'verbose_name_plural': 'Contas'},
        ),
        migrations.AlterModelTable(
            name='conta',
            table='conta',
        ),
    ]
